# Generated by Django 4.2.1 on 2024-06-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_userprofile_referrals_count_alter_userprofile_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='referrals_count',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
