# Generated by Django 4.2.1 on 2024-06-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_userprofile_referrals_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referrals_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
